name: "Add additional info to Issue/PR"
description: ""
author: "Milan Otáhal"
runs:
    using: "node12"
    main: "dist/index.js"
inputs:
    repo-token:
        description: "The GITHUB_TOKEN secret"
        required: true
    pr-body-prefix:
        description: "Additional info to start of PR body (variables {issueNumber}, {prNumber}, {branch})"
        required: false
    pr-body-suffix:
        description: "Additional info to end of PR body (variables {issueNumber}, {prNumber}, {branch})"
        required: false
    issue-body-prefix:
        description: "Additional info to start of Issue body (variables {issueNumber}, {prNumber}, {branch})"
        required: false
    issue-body-suffix:
        description: "Additional info to end of Issue body (variables {issueNumber}, {prNumber}, {branch})"
        required: false
